---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: "provision nodes"
    duffy:
      state: "present"
      count: 1
    register: rnester-ci
  - debug:
      var: rnester-ci
      msg: "JENKINS_EXPORT RHEL_HOST={{rnester.ci}}"
  - command: 'echo "ssid: {{ rnester-ci.ssid }} -- {{ rnester-ci.hosts }}"'
  - name: "teardown nodes from ssid"
    duffy:
      state: "absent"
      ssid: "{{ rnester-ci.ssid }}"
